#访问配置
server:
  port: 8080
  servlet:
    session:
      timeout: 60
    context-path: /
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8

#Spring配置
spring:
  #  Spring数据库配置
  datasource:
#    动态数据源错误
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master 使用 @DS 切换数据源
      datasource:
        master:
          url: jdbc:mysql://10.10.4.170:3306/venue_reservation_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: CVIT2017A412DB!@
          driver-class-name: com.mysql.jdbc.Driver
#        slave_1:
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://xx.xx.xx.xx:3307/dynamic
  thymeleaf:
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html
  mvc:
    view:
      prefix: /html/
      suffix: .html
  #热部署
  devtools:
    restart:
      enabled: false
      #设置重启的目录
      additional-paths: src/main/java
      exclude: WEB-INF/** #classpath目录下的WEB-INF文件夹内容修改不重启
  http:
    log-request-details: false
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis

#Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.wyhy.sbm_demo.model
  type-aliases-super-type: java.lang.Object
# 原生mybatis配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    auto-mapping-unknown-column-behavior: warning
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局策略配置
  global-config:
    refresh: true
    sql-parser-cache: true
    db-config:
      db-type: mysql
      id-type: id_worker
      logic-delete-field: flag  #全局逻辑删除字段
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)